# Generated by Django 3.2.9 on 2021-11-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_figure_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=25)),
                ('issue', models.IntegerField()),
            ],
        ),
    ]
