# Generated by Django 3.2.9 on 2021-11-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comic'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='comics',
            field=models.ManyToManyField(to='main_app.Comic'),
        ),
    ]
